### ISSUE TITLE
阅读体验优化

### ISSUE THREAD

**Issue by Erzbir** [guqing/halo-theme-higan#30]
- 字体过小
- 表格的排版实在太紧凑, 如果字数一多, 就必须用几个空行隔开上下两行有些麻烦
- 标题不明显

希望可以有自定义字体大小的功能, 虽然可以通过 halo 后台的代码注入实现, 但比较麻烦

**Comment by guqing** [comment]
方便提供一个地址看一下吗，你说的是移动端效果还是PC端

**Comment by Erzbir** [comment]
> 方便提供一个地址看一下吗，你说的是移动端效果还是PC端
> 
> 以下是我的博客效果感觉字体应该不小了 https://guqing.xyz/archives/how-to-use-kubenetes
> 
> 因为有标题和正文的字体大小区分如果要配置字体大小可能太麻烦了 

移动端合适桌面端有点小，链接：https://erzbir.com/archives/guide-irish-whistles-buy

表格的部分我用一行 "•" 分开了，不然段落之间会粘在一起看不清是哪一行的

**Comment by guqing** [comment]
移动端看表格确实难以分辨行，我会对表格样式加一个边框，并添加字体大小设置，临时解决方案在全局代码注入的内容注入中添加如下代码：
```css
<style>
  article .content {
    font-size: 0.9rem;
  }
  .highlight pre {
    font-size: 0.9rem;
  }
  article .content table tr {
    border-bottom: 1px dashed var(--color-footer-mobile-2);
  }
  article .content table td {
    padding: 8px 8px;
  }
</style>
```
