### ISSUE TITLE
单行代码段升级后样式丢失

### ISSUE THREAD

**Issue by adozhao** [guqing/halo-theme-higan#65]
文章编辑之后的单行代码样式丢失,以前是虚线包裹，现如今包裹不在，而且字体比较虚弱
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/339eaf7f-00ed-40cf-8f43-4a741568d760)
![edit](https://github.com/guqing/halo-theme-higan/assets/23180747/872305b7-32c8-4098-ae21-70a3cf56a7c5)
![display](https://github.com/guqing/halo-theme-higan/assets/23180747/6aefd851-488e-49ef-8a1e-b82e522531b1)

**Comment by github-ayio** [comment]
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/3cd0ef29-6791-4ed1-9d51-fddb0f69e8ca)

**Comment by guqing** [comment]
非常感谢你能提出这个问题 ♥️，它是上个版本修改出来的 bug，将会在下个版本修复，目前临时的解决办法时通过在 `系统 > 设置 > 代码注入 > 内容页 head 标签` 中添加以下内容来解决：
```css
<style>
  code {
    padding: 0 0.3125rem;
    border: 1px dotted var(--color-meta);
    border-radius: 0.125rem;
  }
  .highlight code {
    padding: none;
    border: none;
    border-radius: unset;
  }
</style>
```
<img width="581" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/40e6553d-8566-44b9-9893-3f2e90e9c33a">
