### ISSUE TITLE
文章引用渲染错误

### ISSUE THREAD

**Issue by github-ado** [guqing/halo-theme-higan#66]
文章编辑的时候引用的内容存在换行，最终渲染效果如下：
halo默认主题最终渲染效果
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/cf9234a3-499a-45e1-9677-7dd69c725fbf)
higan主题最终渲染效果
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/10786239-db5b-4a52-8a86-3e49bb12a456)

**Comment by guqing** [comment]
设计就是如此，实际上不是没有换行，而是 p 标签的 margin 被设置为了 0，如果不设置为 0 显示的时候会不美观

<img width="767" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/ff4af457-3fdc-4843-93b1-dc471d54359a">

**Comment by HowieHz** [comment]
一种可能的解决方案

```css
article .content blockquote p {
  margin: inherit;
  margin-left: 0;
  margin-right: 0;
}

article .content blockquote p:first-child {
  margin-top: 0;
}

article .content blockquote p:last-child {
  margin-bottom: 0;
}
```
