### ISSUE TITLE
开放按照百分比设置文章主体宽度，提升宽屏幕阅读体验

### ISSUE THREAD

**Issue by jalr4ever** [guqing/halo-theme-higan#81]
Hi guqing！

之前在 halo 用过一个叫做寒山志的主题，可以主题设置中自定义显示主体的宽度（按照像素 or 百分比），从而让宽屏显示更加友好

例如，在 4k 分辨率中设置使用 70% 的屏幕宽度居中显示，文章就不会缩成一中间的列

![image](https://github.com/guqing/halo-theme-higan/assets/23929139/38dc6ed2-390b-4fbe-a882-2fe5a0f0c6d4)

期望支持此功能，感谢

**Comment by guqing** [comment]
感谢提出此问题,我会优化一下媒体查询🫡

**Comment by HowieHz** [comment]
你可以通过全局 head 代码注入中加入以下样式覆盖来修改页面最大宽度
以下的示例可以设置为 70% 的页面宽度显示
```css
<style>
  .max-width {
    max-width: 70% !important;
  }
</style>
```

或暂时使用该项目的fork[halo-theme-higan-hz/releases](https://github.com/HowieHz/halo-theme-higan-hz/releases)，此fork提供了该设置选项
