### ISSUE TITLE
行内代码渲染问题

### ISSUE THREAD

**Issue by HowieHz** [guqing/halo-theme-higan#85]
vditor编辑器内
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/30d15272-a047-4daf-80aa-0fda452f0e08)

编辑器内的渲染
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/90138e18-7c36-4583-a405-1fb55bbc15ff)

实际的渲染
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/64a723f2-b282-4e93-b69c-7986b160dede)

👍感谢作者查看我的issue

**Comment by guqing** [comment]
感谢反馈，晚些时候修复，临时解决方案在通过全局 head 代码注入中加入以下样式覆盖看是否解决
```css
<style>
    p {
        text-align:start !important;
    }
</style>
```
